# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_songs_is_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='movie',
            new_name='movie_name',
        ),
    ]
