# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 22:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0004_auto_20170726_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='file_type',
        ),
        migrations.AddField(
            model_name='movies',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movies',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='songs',
            name='audio_file',
            field=models.FileField(default=b'', upload_to=b''),
        ),
    ]
