# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20170729_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='is_favourite',
            new_name='is_favorite',
        ),
    ]
