# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20170729_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_logo',
            field=models.FileField(upload_to=b''),
        ),
    ]
